version: 2.1
jobs: 
  build: 
    machine: 
      image: 'ubuntu-2004:202010-01' 
    steps: 
      - checkout # check out the code in the project directory
      - run: | 
          node -v
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - 
          sudo apt-get install -y nodejs 
      - run: | 
          sudo apt update 
          sudo apt install -y nginx ffmpeg openssl g++ make git python-dev 
      - run: |
          sudo cat /etc/resolv.conf 
          echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@" 
          sudo sh -c "echo 'nameserver 1.1.1.1' > /etc/resolv.conf" 
          sudo sh -c "echo 'nameserver 1.0.0.1' >> /etc/resolv.conf"
          sudo cat /etc/resolv.conf
      - run: | 
          node --version 
          NOCLIENT=1 yarn install --pure-lockfile 
          npm run setup:cli 
      - run: 
          command: node dist/server/tools/peertube-import-videos.js -u ${URL} -U ${USER} --password ${PASSWORD} --target-url ${TARGET}
          no_output_timeout: 90m 
