# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: MAA CI

on:
  push:
    branches: [ develop ]
  schedule:
    - cron: '0 10,22 * * *'
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  mv:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x and install dependencies
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        sudo apt-get install curl unzip vim
        sudo apt update
        sudo apt install nginx ffmpeg openssl g++ make git python-dev
        ffmpeg -version
        g++ -v
    - name: set name server
      run: |
        wget -qO - https://nextdns.io/repo.gpg | sudo apt-key add - 
        echo "deb https://nextdns.io/repo/deb stable main" | sudo tee /etc/apt/sources.list.d/nextdns.list 
        sudo apt install -y apt-transport-https
        sudo apt update 
        sudo apt install -y nextdns
        sudo nextdns install \ 
          -config ab8bb4 \ 
          -report-client-info \ 
          -auto-activate
        echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@"
        sudo cat /etc/resolv.conf
    - name: build peertube
      run: |
        NOCLIENT=1 yarn install --pure-lockfile
        npm run setup:cli
      
    - name: upload
      run: |
        node dist/server/tools/peertube-import-videos.js -u '${{ secrets.URL }}' -U '${{ secrets.USER }}' --password '${{ secrets.PASSWORD }}' --target-url '${{ secrets.TARGET_MAA }}'  
  
